### ISSUE TITLE
What about docker image?

### ISSUE THREAD

**Issue by jifeon** [joker1007/yaml_vault#1]
Hey! Such a nice lib, I'm going to use it to encrypt my config files for [rancher](http://rancher.com/), batch of  `docker-compose` and `rancher-compose` yaml files and share them between our team members then. But we do not use ruby, does not have `gem` installed etc. and do not want to install it :) I'm going to make docker image with `yaml_vault` as a service. Are you interested in getting PR with Dockerfile and publishing repo on docker hub?

**Comment by joker1007** [comment]
Thanks!
I merged it.
